application: buzz-referee
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /admin*
  script: admin.py
  login: admin

- url: /ref
  script: main.py

- url: .*
  script: main.py
